[package]
name = "designitex"
version = "0.1.0"
edition = '2021'

[dependencies]
tree-sitter = "0.23"
tree-sitter-java = "0.23"
tree-sitter-python = "0.23"
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
cc = "*"
